title: гцтffѫп
description: Library of my thoughts.
author: lutffmn
email: lutffmn@gmail.com
show_excerpts: true
theme: minima
baseurl: "" # Do not change for user/organization site
url: "https://lutffmn.github.io"
