title: lutffmn's Blog
description: Welcome to my Jekyll blog powered by GitHub Pages!
author: lutffmn
email: your-email@example.com
show_excerpts: true
theme: minima
baseurl: "" # Do not change for user/organization site
url: "https://lutffmn.github.io"
